# post criar jogo

POST http://localhost:8080/quiz/iniciarjogo
Content-Type: application/json

{
    "apelido": "Lipe",
    "quantidadePerguntas": 2
}

###

#POST para responder uma pergunta

POST http://localhost:8080/quiz/6/perguntas/7/resposta
Content-Type: application/json

{
    "respostaJogador": "a"
}

#get para obter o ranking
GET http://localhost:8080/quiz/ranking